### ISSUE TITLE
Slow on large projects

### ISSUE THREAD

**Issue by alesf** [jotson/SublimePHPIntel#10]
I see a lot of spinning rainbows.
It slows down coding so much it's distracting.
Would it be possible that it would scan the project only when saving a file or just manually?

**Comment by jotson** [comment]
It does that now. It only scans the entire project manually. And when you
save, it only scans that one file. Are you sure it is scanning?

**Comment by koko236** [comment]
Also slow with a single 3 lines php file. I don't know how to narow it down but after every 'Enter' pressed ST3 freezes for 2-3 seconds with very high cpu usage. I run it on Windows 7 with i5 and 8GB RAM. Quite fresh system install, other ST plugins are ColorPicker, Compare SideBySide and Processing. Had to uninstall the plugin for now.

**Comment by jotson** [comment]
If you open a terminal window and run:

`php -r "echo json_encode(token_get_all(file_get_contents('/path/to/source/code.php')));"`

Does that take a long time to run?

**Comment by koko236** [comment]
if I add microtime() in front and at the end of the command there's about 3 ms difference. Without the echo it's more like 1ms. Now when I think of it, I might have had two folders open in ST the other one being fresh Symfony2 project, so maybe that would count as a medium sized project? I can check that as well. Anyway I didn't save anything, I just hit 'enter' and had very noticeable editor freeze. .

**Comment by koko236** [comment]
No, I removed the other folder, reinstalled PHPIntel and there's the freeze again.

**Comment by jotson** [comment]
I think I fixed this. Let me know if 1.0.4 works for you.

**Comment by koko236** [comment]
Sure, any idea when will it be available through the Package Manager? (At the moment PM lists 1.0.3).

**Comment by koko236** [comment]
It works fine now! Thanks a lot for the fix!
