### ISSUE TITLE
Matching any number of optional arguments

### ISSUE THREAD

**Issue by lozcalver** [jotson/SublimePHPIntel#12]
Hi,

I’m trying to write a factory pattern that matches the following:

``` php
SomeClass::create();
SomeClass::create('arg1');
SomeClass::create('arg1' ... 'argx'); // Any number of args
```

Each of them returns an instance of `SomeClass`. I’ve tried every combination I can think of, but can’t seem to get any to work (admittedly, I suck at regular expressions, so it could just be my fault). E.g:

``` json
{
    "pattern": "(.*?)::create\\((.*?)\\)",
    "class": "%1"
}
```

The only one I could get to work is the first example from above, with this:

``` json
{
    "pattern": "(.*?)::create\\(\\)",
    "class": "%1"
}
```

Any tips?

**Comment by jotson** [comment]
In your example, returning SomeClass looks correct. %1 is the first matching pattern which in your example is SomeClass. What do you expect it to return instead?

**Comment by jotson** [comment]
Oh, duh, I think I understand what you're talking about now. They _should_ all return SomeClass but only the first one works... :-) Let me do some testing and get back to you.

**Comment by jotson** [comment]
I think this might be related to the order the patterns appear in your settings. Patterns are applied in the order that they appear in the file. So you need to put the most specific patterns first and then more general patterns later. Try putting that first pattern at the top of file.

**Comment by lozcalver** [comment]
Thanks for looking into this @jotson. The first pattern from above is actually working, I’ve no idea what I was doing wrong yesterday!

**Comment by lozcalver** [comment]
Okay, it _was_ working, but now definitely isn’t! Something fishy’s going on here, I’ll try to track it down

**Comment by lozcalver** [comment]
I think I’ve tracked it down, though I don’t know Python at all so I may be off. But it looks like the regular expressions are only matched once per file. If you type out the example below, the first line matches but the second line doesn’t:

``` json
{
    "pattern": "(.*?)::create\\((.*?)\\)",
    "class": "%1"
}
```

``` php
SomeObject::create('test', 'test')->someMethod(); // Works, someMethod is suggested
SomeObject::create('test', 'test')->someMethod(); // Doesn't work, someMethod is not suggested
```

**Comment by jotson** [comment]
I just pushed version 1.0.5 which should fix that issue. It can take a few hours before it shows up in Package Control. Please close the issue if that fixes it for you.
