### ISSUE TITLE
Multiple cursor broken

### ISSUE THREAD

**Issue by Shnilj** [jotson/SublimePHPIntel#9]
Hey,

I installed this plugin because it looked pretty cool and easy to use, but whenever I install it the multiple cursors in ST3 stop working. This for me is the main reason I won't be using this plugin...

When this issue is fixed, I'll gladly use this plugin, but the multicursor-functionality is kind of a big one for me.

Thanks!

**Comment by jotson** [comment]
I use that feature every day. How exactly are you trying to activate multiple cursors?

**Comment by Shnilj** [comment]
I just use the command-key to place multiple cursors. When I try this while using PHPIntel, it does not seem to work. When I then uninstall PHPIntel, it starts working again.

**Comment by Shnilj** [comment]
Sorry! Didn't mean to close the issue!

**Comment by jotson** [comment]
There are at least four ways I know of to enable multiple cursors. Which
keys are you pressing *exactly*?

**Comment by Shnilj** [comment]
I just use the "hold command-key and click"-method to add cursors, basically.

**Comment by jotson** [comment]
Completely forgot about the mousemap files. Undocumented, unused, and broken so I removed them. Should be fixed now. Thanks.

**Comment by Shnilj** [comment]
Thanks for the fix!
